#!/usr/bin/env python

import os, subprocess, sys

cmdlines = []
ps = subprocess.Popen(["ps", "-Ao", "command"], stdout=subprocess.PIPE)
for cmdline in ps.stdout:
    # Remove ending newline
    cmdlines.append(cmdline[:-1])

cmd = ' '.join(sys.argv[1:])
if cmd not in cmdlines:
    os.system(cmd)
